version: "3.6"

services:
  sd35-txt2img1:
    image: llms/txt2img:2.0
    container_name: sd35-txt2img1
    ports:
      - "11002:80"
    restart: always
    volumes:
      - ./generate_pics:/app/generate_pics
      - /data/dev/model-checkpoint:/data/dev/model-checkpoint
    command: /bin/bash -c "pip uninstall apex -y && uvicorn app:app --host 0.0.0.0 --port 80 --log-level info --workers 1 --timeout-keep-alive 5"
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              device_ids: [ "6" ]
              capabilities: [ "gpu" ]
    healthcheck:
      test: "curl --fail --request GET 'localhost:80' || exit 1"
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s

